# Netlist Viewer TCL File
set_family -name IGLOO2
top_module -name DRM2_top
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/PXLIF/PXLIF_0/rtl/vhdl/core/corefifo_NstagesSync.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/PXLIF/PXLIF_0/rtl/vhdl/core/corefifo_grayToBinConv.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/Actel/DirectCore/COREFIFO/2.7.105/rtl/vhdl/core/fifo_pkg.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/PXLIF/PXLIF_0/rtl/vhdl/core/corefifo_async.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/PXLIF/PXLIF_0/rtl/vhdl/core/corefifo_fwft.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/PXLIF/PXLIF_0/rtl/vhdl/core/corefifo_resetSync.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/PXLIF/PXLIF_0/rtl/vhdl/core/corefifo_sync.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/PXLIF/PXLIF_0/rtl/vhdl/core/corefifo_sync_scntr.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/PXLIF/PXLIF_0/rtl/vhdl/core/PXLIF_PXLIF_0_LSRAM_top.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/PXLIF/PXLIF_0/rtl/vhdl/core/PXLIF_PXLIF_0_ram_wrapper.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/PXLIF/PXLIF_0/rtl/vhdl/core/COREFIFO.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/PXLIF/PXLIF.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/PXLOF/PXLOF_0/rtl/vhdl/core/corefifo_NstagesSync.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/PXLOF/PXLOF_0/rtl/vhdl/core/corefifo_grayToBinConv.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/PXLOF/PXLOF_0/rtl/vhdl/core/corefifo_async.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/PXLOF/PXLOF_0/rtl/vhdl/core/corefifo_fwft.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/PXLOF/PXLOF_0/rtl/vhdl/core/corefifo_resetSync.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/PXLOF/PXLOF_0/rtl/vhdl/core/corefifo_sync.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/PXLOF/PXLOF_0/rtl/vhdl/core/corefifo_sync_scntr.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/PXLOF/PXLOF_0/rtl/vhdl/core/PXLOF_PXLOF_0_LSRAM_top.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/PXLOF/PXLOF_0/rtl/vhdl/core/PXLOF_PXLOF_0_ram_wrapper.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/PXLOF/PXLOF_0/rtl/vhdl/core/COREFIFO.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/PXLOF/PXLOF.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/hdl/DRM2pkg.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/hdl/a1500_interf.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/hdl/caenlinkpkg.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/hdl/clint.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/RL/RL_0/rtl/vhdl/core/corefifo_fwft.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/RL/RL_0/rtl/vhdl/core/corefifo_resetSync.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/RL/RL_0/rtl/vhdl/core/corefifo_sync_scntr.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/RL/RL_0/rtl/vhdl/core/corefifo_sync.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/RL/RL_0/rtl/vhdl/core/corefifo_NstagesSync.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/RL/RL_0/rtl/vhdl/core/corefifo_grayToBinConv.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/RL/RL_0/rtl/vhdl/core/corefifo_async.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/RL/RL_0/rtl/vhdl/core/RL_RL_0_LSRAM_top.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/RL/RL_0/rtl/vhdl/core/RL_RL_0_ram_wrapper.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/RL/RL_0/rtl/vhdl/core/COREFIFO.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/RL/RL.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/TL/TL_0/rtl/vhdl/core/corefifo_fwft.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/TL/TL_0/rtl/vhdl/core/corefifo_resetSync.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/TL/TL_0/rtl/vhdl/core/corefifo_sync_scntr.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/TL/TL_0/rtl/vhdl/core/corefifo_sync.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/TL/TL_0/rtl/vhdl/core/corefifo_NstagesSync.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/TL/TL_0/rtl/vhdl/core/corefifo_grayToBinConv.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/TL/TL_0/rtl/vhdl/core/corefifo_async.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/TL/TL_0/rtl/vhdl/core/TL_TL_0_LSRAM_top.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/TL/TL_0/rtl/vhdl/core/TL_TL_0_ram_wrapper.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/TL/TL_0/rtl/vhdl/core/COREFIFO.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/TL/TL.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/hdl/conet_interf.vhd}
addfile -view RTL -lib COREPCS_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/Actel/DirectCore/CorePCS/3.3.100/rtl/vhdl/core/DEC_ERR.vhd}
addfile -view RTL -lib COREPCS_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/Actel/DirectCore/CorePCS/3.3.100/rtl/vhdl/core/DEC_DATA.vhd}
addfile -view RTL -lib COREPCS_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/Actel/DirectCore/CorePCS/3.3.100/rtl/vhdl/core/DEC_RD_U.vhd}
addfile -view RTL -lib COREPCS_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/Actel/DirectCore/CorePCS/3.3.100/rtl/vhdl/core/SYNC_FSM.vhd}
addfile -view RTL -lib COREPCS_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/Actel/DirectCore/CorePCS/3.3.100/rtl/vhdl/core/DECODER_CI.vhd}
addfile -view RTL -lib COREPCS_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/Actel/DirectCore/CorePCS/3.3.100/rtl/vhdl/core/DEC_RD_L.vhd}
addfile -view RTL -lib COREPCS_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/Actel/DirectCore/CorePCS/3.3.100/rtl/vhdl/core/DECODER_CO.vhd}
addfile -view RTL -lib COREPCS_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/Actel/DirectCore/CorePCS/3.3.100/rtl/vhdl/core/WORD_ALIGNER_20.vhd}
addfile -view RTL -lib COREPCS_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/Actel/DirectCore/CorePCS/3.3.100/rtl/vhdl/core/DEC_WA.vhd}
addfile -view RTL -lib COREPCS_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/Actel/DirectCore/CorePCS/3.3.100/rtl/vhdl/core/DEC_RD.vhd}
addfile -view RTL -lib COREPCS_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/Actel/DirectCore/CorePCS/3.3.100/rtl/vhdl/core/DECODER.vhd}
addfile -view RTL -lib COREPCS_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/Actel/DirectCore/CorePCS/3.3.100/rtl/vhdl/core/MUX4X1.vhd}
addfile -view RTL -lib COREPCS_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/Actel/DirectCore/CorePCS/3.3.100/rtl/vhdl/core/MUX32X1.vhd}
addfile -view RTL -lib COREPCS_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/Actel/DirectCore/CorePCS/3.3.100/rtl/vhdl/core/MUX32X6.vhd}
addfile -view RTL -lib COREPCS_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/Actel/DirectCore/CorePCS/3.3.100/rtl/vhdl/core/ENC_D.vhd}
addfile -view RTL -lib COREPCS_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/Actel/DirectCore/CorePCS/3.3.100/rtl/vhdl/core/ENC_FLIP.vhd}
addfile -view RTL -lib COREPCS_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/Actel/DirectCore/CorePCS/3.3.100/rtl/vhdl/core/ENC_K.vhd}
addfile -view RTL -lib COREPCS_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/Actel/DirectCore/CorePCS/3.3.100/rtl/vhdl/core/ENCODER.vhd}
addfile -view RTL -lib COREPCS_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/Actel/DirectCore/CorePCS/3.3.100/rtl/vhdl/core/BUF_DATA.vhd}
addfile -view RTL -lib COREPCS_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/Actel/DirectCore/CorePCS/3.3.100/rtl/vhdl/core/ENCODER_L.vhd}
addfile -view RTL -lib COREPCS_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/Actel/DirectCore/CorePCS/3.3.100/rtl/vhdl/core/ENCODER_N.vhd}
addfile -view RTL -lib COREPCS_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/Actel/DirectCore/CorePCS/3.3.100/rtl/vhdl/core/ENCODER_U.vhd}
addfile -view RTL -lib COREPCS_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/Actel/DirectCore/CorePCS/3.3.100/rtl/vhdl/core/ENCODER_16B20B.vhd}
addfile -view RTL -lib COREPCS_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/Actel/DirectCore/CorePCS/3.3.100/rtl/vhdl/core/WORD_ALIGNER_10.vhd}
addfile -view RTL -lib COREPCS_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/Actel/DirectCore/CorePCS/3.3.100/rtl/vhdl/core/corepcs_pkg.vhd}
addfile -view RTL -lib COREPCS_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/Actel/DirectCore/CorePCS/3.3.100/rtl/vhdl/core/CorePCS.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/Core_PCS/Core_PCS.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/EPCS_SERDES_IF/EPCS_SERDES_IF_0/EPCS_SERDES_IF_EPCS_SERDES_IF_0_SERDES_IF2_syn.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/EPCS_SERDES_IF/EPCS_SERDES_IF_0/EPCS_SERDES_IF_EPCS_SERDES_IF_0_SERDES_IF2.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/EPCS_SERDES_IF/EPCS_SERDES_IF.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/hdl/delay_line.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/hdl/epcs_rx_intf.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/hdl/epcs_tx_intf.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/hdl/EPCS_SERDES.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/hdl/FDIV.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/hdl/CAEN_LINK.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/EPCS_Demo_sb/CCC_0/EPCS_Demo_sb_CCC_0_FCCC.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/Actel/SgCore/OSC/2.0.101/osc_comps.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/EPCS_Demo_sb/FABOSC_0/EPCS_Demo_sb_FABOSC_0_OSC.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/EPCS_Demo_sb_HPMS/EPCS_Demo_sb_HPMS_syn.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/EPCS_Demo_sb_HPMS/EPCS_Demo_sb_HPMS.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/Actel/DirectCore/CoreConfigMaster/2.1.102/rtl/vhdl/core/coreconfigmaster.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/Actel/DirectCore/CoreConfigP/7.1.100/rtl/vhdl/core/coreconfigp.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/Actel/DirectCore/CoreResetP/7.1.100/rtl/vhdl/core/coreresetp_pcie_hotreset.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/Actel/DirectCore/CoreResetP/7.1.100/rtl/vhdl/core/coreresetp.vhd}
addfile -view RTL -lib COREAHBLITE_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/Actel/DirectCore/CoreAHBLite/5.2.100/rtl/vhdl/core/coreahblite_slavearbiter.vhd}
addfile -view RTL -lib COREAHBLITE_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/Actel/DirectCore/CoreAHBLite/5.2.100/rtl/vhdl/core/coreahblite_slavestage.vhd}
addfile -view RTL -lib COREAHBLITE_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/Actel/DirectCore/CoreAHBLite/5.2.100/rtl/vhdl/core/coreahblite_defaultslavesm.vhd}
addfile -view RTL -lib COREAHBLITE_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/Actel/DirectCore/CoreAHBLite/5.2.100/rtl/vhdl/core/coreahblite_addrdec.vhd}
addfile -view RTL -lib COREAHBLITE_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/Actel/DirectCore/CoreAHBLite/5.2.100/rtl/vhdl/core/coreahblite_masterstage.vhd}
addfile -view RTL -lib COREAHBLITE_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/Actel/DirectCore/CoreAHBLite/5.2.100/rtl/vhdl/core/coreahblite_matrix4x16.vhd}
addfile -view RTL -lib COREAHBLITE_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/Actel/DirectCore/CoreAHBLite/5.2.100/rtl/vhdl/core/coreahblite_pkg.vhd}
addfile -view RTL -lib COREAHBLITE_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/Actel/DirectCore/CoreAHBLite/5.2.100/rtl/vhdl/core/coreahblite.vhd}
addfile -view RTL -lib COREAHBLITE_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/Actel/DirectCore/CoreAHBLite/5.2.100/rtl/vhdl/core/components.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/EPCS_Demo_sb/EPCS_Demo_sb.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/GBTx_data_fifo/GBTx_data_fifo_0/rtl/vhdl/core/corefifo_fwft.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/GBTx_data_fifo/GBTx_data_fifo_0/rtl/vhdl/core/corefifo_resetSync.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/GBTx_data_fifo/GBTx_data_fifo_0/rtl/vhdl/core/corefifo_sync_scntr.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/GBTx_data_fifo/GBTx_data_fifo_0/rtl/vhdl/core/corefifo_sync.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/GBTx_data_fifo/GBTx_data_fifo_0/rtl/vhdl/core/corefifo_NstagesSync.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/GBTx_data_fifo/GBTx_data_fifo_0/rtl/vhdl/core/corefifo_grayToBinConv.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/GBTx_data_fifo/GBTx_data_fifo_0/rtl/vhdl/core/corefifo_async.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/GBTx_data_fifo/GBTx_data_fifo_0/rtl/vhdl/core/GBTx_data_fifo_GBTx_data_fifo_0_LSRAM_top.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/GBTx_data_fifo/GBTx_data_fifo_0/rtl/vhdl/core/GBTx_data_fifo_GBTx_data_fifo_0_ram_wrapper.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/GBTx_data_fifo/GBTx_data_fifo_0/rtl/vhdl/core/COREFIFO.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/GBTx_data_fifo/GBTx_data_fifo.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/fake_l1msg_fifo/fake_l1msg_fifo_0/rtl/vhdl/core/corefifo_sync_scntr.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/fake_l1msg_fifo/fake_l1msg_fifo_0/rtl/vhdl/core/fake_l1msg_fifo_fake_l1msg_fifo_0_USRAM_top.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/fake_l1msg_fifo/fake_l1msg_fifo_0/rtl/vhdl/core/fake_l1msg_fifo_fake_l1msg_fifo_0_ram_wrapper.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/fake_l1msg_fifo/fake_l1msg_fifo_0/rtl/vhdl/core/corefifo_NstagesSync.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/fake_l1msg_fifo/fake_l1msg_fifo_0/rtl/vhdl/core/corefifo_grayToBinConv.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/fake_l1msg_fifo/fake_l1msg_fifo_0/rtl/vhdl/core/corefifo_async.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/fake_l1msg_fifo/fake_l1msg_fifo_0/rtl/vhdl/core/corefifo_fwft.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/fake_l1msg_fifo/fake_l1msg_fifo_0/rtl/vhdl/core/corefifo_resetSync.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/fake_l1msg_fifo/fake_l1msg_fifo_0/rtl/vhdl/core/corefifo_sync.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/fake_l1msg_fifo/fake_l1msg_fifo_0/rtl/vhdl/core/COREFIFO.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/fake_l1msg_fifo/fake_l1msg_fifo.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/hdl/fake_gbt.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/l1msg_gbtck/l1msg_gbtck_0/rtl/vhdl/core/corefifo_sync_scntr.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/l1msg_gbtck/l1msg_gbtck_0/rtl/vhdl/core/l1msg_gbtck_l1msg_gbtck_0_USRAM_top.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/l1msg_gbtck/l1msg_gbtck_0/rtl/vhdl/core/l1msg_gbtck_l1msg_gbtck_0_ram_wrapper.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/l1msg_gbtck/l1msg_gbtck_0/rtl/vhdl/core/corefifo_NstagesSync.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/l1msg_gbtck/l1msg_gbtck_0/rtl/vhdl/core/corefifo_grayToBinConv.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/l1msg_gbtck/l1msg_gbtck_0/rtl/vhdl/core/corefifo_async.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/l1msg_gbtck/l1msg_gbtck_0/rtl/vhdl/core/corefifo_fwft.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/l1msg_gbtck/l1msg_gbtck_0/rtl/vhdl/core/corefifo_resetSync.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/l1msg_gbtck/l1msg_gbtck_0/rtl/vhdl/core/corefifo_sync.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/l1msg_gbtck/l1msg_gbtck_0/rtl/vhdl/core/COREFIFO.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/l1msg_gbtck/l1msg_gbtck.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/l1msg/l1msg_0/rtl/vhdl/core/corefifo_NstagesSync.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/l1msg/l1msg_0/rtl/vhdl/core/corefifo_grayToBinConv.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/l1msg/l1msg_0/rtl/vhdl/core/corefifo_async.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/l1msg/l1msg_0/rtl/vhdl/core/l1msg_l1msg_0_USRAM_top.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/l1msg/l1msg_0/rtl/vhdl/core/l1msg_l1msg_0_ram_wrapper.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/l1msg/l1msg_0/rtl/vhdl/core/corefifo_fwft.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/l1msg/l1msg_0/rtl/vhdl/core/corefifo_resetSync.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/l1msg/l1msg_0/rtl/vhdl/core/corefifo_sync_scntr.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/l1msg/l1msg_0/rtl/vhdl/core/corefifo_sync.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/l1msg/l1msg_0/rtl/vhdl/core/COREFIFO.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/l1msg/l1msg.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/trigger_fifo/trigger_fifo_0/rtl/vhdl/core/corefifo_NstagesSync.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/trigger_fifo/trigger_fifo_0/rtl/vhdl/core/corefifo_grayToBinConv.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/trigger_fifo/trigger_fifo_0/rtl/vhdl/core/corefifo_async.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/trigger_fifo/trigger_fifo_0/rtl/vhdl/core/trigger_fifo_trigger_fifo_0_USRAM_top.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/trigger_fifo/trigger_fifo_0/rtl/vhdl/core/trigger_fifo_trigger_fifo_0_ram_wrapper.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/trigger_fifo/trigger_fifo_0/rtl/vhdl/core/corefifo_fwft.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/trigger_fifo/trigger_fifo_0/rtl/vhdl/core/corefifo_resetSync.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/trigger_fifo/trigger_fifo_0/rtl/vhdl/core/corefifo_sync_scntr.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/trigger_fifo/trigger_fifo_0/rtl/vhdl/core/corefifo_sync.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/trigger_fifo/trigger_fifo_0/rtl/vhdl/core/COREFIFO.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/trigger_fifo/trigger_fifo.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/hdl/GBTx_interface.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/hdl/AUX_CTRL.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/hdl/GBTX_CTRL.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/hdl/GBTX_DECODER.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/hdl/GBTX_SWITCH.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/hdl/ErrorDebugI2C.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/hdl/I2CErrorConv.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/hdl/I2CSFPTEMPctrl.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/I2CSFTTEMP/URAM_0/I2CSFTTEMP_URAM_0_URAM.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/hdl/COREI2C_Bit2Bus.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/hdl/COREI2C_Bus2Bit.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/hdl/I2CStateMachineMASTERctrl.vhd}
addfile -view RTL -lib COREI2C_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/Actel/DirectCore/COREI2C/7.2.101/rtl/vhdl/core/corei2creal.vhd}
addfile -view RTL -lib COREI2C_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/I2C_masterFIFO/COREI2C_0/rtl/vhdl/core/corei2c.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/I2C_masterFIFO/FIFO_IN/rtl/vhdl/core/corefifo_NstagesSync.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/I2C_masterFIFO/FIFO_IN/rtl/vhdl/core/corefifo_grayToBinConv.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/I2C_masterFIFO/FIFO_IN/rtl/vhdl/core/corefifo_async.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/I2C_masterFIFO/FIFO_IN/rtl/vhdl/core/corefifo_resetSync.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/I2C_masterFIFO/FIFO_IN/rtl/vhdl/core/corefifo_sync.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/I2C_masterFIFO/FIFO_IN/rtl/vhdl/core/corefifo_fwft.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/I2C_masterFIFO/FIFO_IN/rtl/vhdl/core/corefifo_sync_scntr.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/I2C_masterFIFO/FIFO_IN/rtl/vhdl/core/I2C_masterFIFO_FIFO_IN_USRAM_top.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/I2C_masterFIFO/FIFO_IN/rtl/vhdl/core/I2C_masterFIFO_FIFO_IN_ram_wrapper.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/I2C_masterFIFO/FIFO_IN/rtl/vhdl/core/COREFIFO.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/I2C_masterFIFO/FIFO_OUT/rtl/vhdl/core/corefifo_NstagesSync.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/I2C_masterFIFO/FIFO_OUT/rtl/vhdl/core/corefifo_grayToBinConv.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/I2C_masterFIFO/FIFO_OUT/rtl/vhdl/core/corefifo_async.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/I2C_masterFIFO/FIFO_OUT/rtl/vhdl/core/corefifo_resetSync.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/I2C_masterFIFO/FIFO_OUT/rtl/vhdl/core/corefifo_sync.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/I2C_masterFIFO/FIFO_OUT/rtl/vhdl/core/corefifo_fwft.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/I2C_masterFIFO/FIFO_OUT/rtl/vhdl/core/corefifo_sync_scntr.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/I2C_masterFIFO/FIFO_OUT/rtl/vhdl/core/I2C_masterFIFO_FIFO_OUT_USRAM_top.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/I2C_masterFIFO/FIFO_OUT/rtl/vhdl/core/I2C_masterFIFO_FIFO_OUT_ram_wrapper.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/I2C_masterFIFO/FIFO_OUT/rtl/vhdl/core/COREFIFO.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/I2C_masterFIFO/I2C_masterFIFO.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/I2CSFTTEMP/I2CSFTTEMP.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/hdl/GBTXI2C_CTRL.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/hdl/I2CStateMachineGBTXv2.vhd}
addfile -view RTL -lib COREI2C_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/I2C_GBTX/COREI2C_0/rtl/vhdl/core/corei2c.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/I2C_GBTX/FIFO_IN/rtl/vhdl/core/corefifo_NstagesSync.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/I2C_GBTX/FIFO_IN/rtl/vhdl/core/corefifo_grayToBinConv.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/I2C_GBTX/FIFO_IN/rtl/vhdl/core/corefifo_async.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/I2C_GBTX/FIFO_IN/rtl/vhdl/core/corefifo_fwft.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/I2C_GBTX/FIFO_IN/rtl/vhdl/core/corefifo_resetSync.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/I2C_GBTX/FIFO_IN/rtl/vhdl/core/corefifo_sync.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/I2C_GBTX/FIFO_IN/rtl/vhdl/core/corefifo_sync_scntr.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/I2C_GBTX/FIFO_IN/rtl/vhdl/core/I2C_GBTX_FIFO_IN_LSRAM_top.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/I2C_GBTX/FIFO_IN/rtl/vhdl/core/I2C_GBTX_FIFO_IN_ram_wrapper.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/I2C_GBTX/FIFO_IN/rtl/vhdl/core/COREFIFO.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/I2C_GBTX/FIFO_OUT/rtl/vhdl/core/corefifo_NstagesSync.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/I2C_GBTX/FIFO_OUT/rtl/vhdl/core/corefifo_grayToBinConv.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/I2C_GBTX/FIFO_OUT/rtl/vhdl/core/corefifo_async.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/I2C_GBTX/FIFO_OUT/rtl/vhdl/core/corefifo_fwft.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/I2C_GBTX/FIFO_OUT/rtl/vhdl/core/corefifo_resetSync.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/I2C_GBTX/FIFO_OUT/rtl/vhdl/core/corefifo_sync.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/I2C_GBTX/FIFO_OUT/rtl/vhdl/core/corefifo_sync_scntr.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/I2C_GBTX/FIFO_OUT/rtl/vhdl/core/I2C_GBTX_FIFO_OUT_LSRAM_top.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/I2C_GBTX/FIFO_OUT/rtl/vhdl/core/I2C_GBTX_FIFO_OUT_ram_wrapper.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/I2C_GBTX/FIFO_OUT/rtl/vhdl/core/COREFIFO.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/I2C_GBTX/I2C_GBTX.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/hdl/I2CStateMachineSlaveAUX.vhd}
addfile -view RTL -lib COREI2C_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/I2C_SlaveFIFO/COREI2C_0/rtl/vhdl/core/corei2c.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/I2C_SlaveFIFO/I2C_SlaveFIFO.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/hdl/TestSignal.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/hdl/DivVar16bit.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/hdl/DivVar4bit.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/hdl/DivVar8bit.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/Timer100ms/Timer100ms.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/hdl/Versioning.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/I2C_CORE/I2C_CORE.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/srof_fifo/srof_fifo_0/rtl/vhdl/core/corefifo_sync_scntr.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/srof_fifo/srof_fifo_0/rtl/vhdl/core/srof_fifo_srof_fifo_0_LSRAM_top.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/srof_fifo/srof_fifo_0/rtl/vhdl/core/srof_fifo_srof_fifo_0_ram_wrapper.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/srof_fifo/srof_fifo_0/rtl/vhdl/core/corefifo_NstagesSync.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/srof_fifo/srof_fifo_0/rtl/vhdl/core/corefifo_grayToBinConv.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/srof_fifo/srof_fifo_0/rtl/vhdl/core/corefifo_async.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/srof_fifo/srof_fifo_0/rtl/vhdl/core/corefifo_fwft.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/srof_fifo/srof_fifo_0/rtl/vhdl/core/corefifo_resetSync.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/srof_fifo/srof_fifo_0/rtl/vhdl/core/corefifo_sync.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/srof_fifo/srof_fifo_0/rtl/vhdl/core/COREFIFO.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/srof_fifo/srof_fifo.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/hdl/rod_sniffer.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/hdl/version_reg.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/hdl/bus_extender.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/int_sram/int_sram_0/int_sram_int_sram_0_TPSRAM.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/int_sram/int_sram.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/local_bcid/local_bcid_0/rtl/vhdl/core/corefifo_sync_scntr.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/local_bcid/local_bcid_0/rtl/vhdl/core/local_bcid_local_bcid_0_USRAM_top.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/local_bcid/local_bcid_0/rtl/vhdl/core/local_bcid_local_bcid_0_ram_wrapper.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/local_bcid/local_bcid_0/rtl/vhdl/core/corefifo_NstagesSync.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/local_bcid/local_bcid_0/rtl/vhdl/core/corefifo_grayToBinConv.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/local_bcid/local_bcid_0/rtl/vhdl/core/corefifo_async.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/local_bcid/local_bcid_0/rtl/vhdl/core/corefifo_fwft.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/local_bcid/local_bcid_0/rtl/vhdl/core/corefifo_resetSync.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/local_bcid/local_bcid_0/rtl/vhdl/core/corefifo_sync.vhd}
addfile -view RTL -lib COREFIFO_LIB -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/local_bcid/local_bcid_0/rtl/vhdl/core/COREFIFO.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/component/work/local_bcid/local_bcid.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/hdl/vme_int.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/hdl/txt_util.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/hdl/DRM2_top.vhd}
addfile -view HIER -lib work -type EDIF -mode NONE -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/synthesis/DRM2_top.edn}
addfile -view FLAT -lib work -type AFL -mode NONE -name {E:/alicetof/firmware/DRM2_rev2.0/DRM2_Ztenth_fw_trm_12.5/designer/DRM2_top/DRM2_top.afl}