@TM:1240415196
@W:  :"":0:0:0:-1|Net N_217 appears to be a clock source which was not identified. Assuming default frequency. 
@TM:1240400997
@W:  :"":0:0:0:-1|Net CLEAR_0 appears to be a clock source which was not identified. Assuming default frequency. 
@TM:1239285513
@W:  :"":0:0:0:-1|Constraints on tristate nets are currently not supported
@N: MF176 :"":0:0:0:-1|Default generator successful 
@N: MF249 :"":0:0:0:-1|Running in 32-bit mode.
@W: MO111 :"":0:0:0:-1|tristate driver un1_I7_t[5] on net un1_I7[5] has its enable tied to GND (module v1392ltm) 
@W: MO111 :"":0:0:0:-1|tristate driver un1_I7_t[4] on net un1_I7[4] has its enable tied to GND (module v1392ltm) 
@W: MO111 :"":0:0:0:-1|tristate driver un1_I7_t[3] on net un1_I7[3] has its enable tied to GND (module v1392ltm) 
@W: MO111 :"":0:0:0:-1|tristate driver un1_I7_t[2] on net un1_I7[2] has its enable tied to GND (module v1392ltm) 
@W: MO111 :"":0:0:0:-1|tristate driver un1_I7_t[1] on net un1_I7[1] has its enable tied to GND (module v1392ltm) 
@W: MO111 :"":0:0:0:-1|tristate driver un1_I7_t[0] on net un1_I7[0] has its enable tied to GND (module v1392ltm) 
@W: MO111 :"":0:0:0:-1|tristate driver N_9_t on net N_9 has its enable tied to GND (module v1392ltm) 
@W: MO111 :"":0:0:0:-1|tristate driver N_8_t on net N_8 has its enable tied to GND (module v1392ltm) 
@W: MO111 :"":0:0:0:-1|tristate driver N_7_t on net N_7 has its enable tied to GND (module v1392ltm) 
@W: MO111 :"":0:0:0:-1|tristate driver N_6_t on net N_6 has its enable tied to GND (module v1392ltm) 
@W: MO111 :"":0:0:0:-1|tristate driver N_5_t on net N_5 has its enable tied to GND (module v1392ltm) 
@W: MO111 :"":0:0:0:-1|tristate driver N_4_t on net N_4 has its enable tied to GND (module v1392ltm) 
@W: MO111 :"":0:0:0:-1|tristate driver N_42_t on net N_42 has its enable tied to GND (module v1392ltm) 
@W: MO111 :"":0:0:0:-1|tristate driver N_41_t on net N_41 has its enable tied to GND (module v1392ltm) 
@W: MO111 :"":0:0:0:-1|tristate driver N_40_t on net N_40 has its enable tied to GND (module v1392ltm) 
@W: MO111 :"":0:0:0:-1|tristate driver N_3_t on net N_3 has its enable tied to GND (module v1392ltm) 
@W: MO111 :"":0:0:0:-1|tristate driver N_39_t on net N_39 has its enable tied to GND (module v1392ltm) 
@W: MO111 :"":0:0:0:-1|tristate driver N_38_t on net N_38 has its enable tied to GND (module v1392ltm) 
@W: MO111 :"":0:0:0:-1|tristate driver N_37_t on net N_37 has its enable tied to GND (module v1392ltm) 
@W: MO111 :"":0:0:0:-1|tristate driver N_36_t on net N_36 has its enable tied to GND (module v1392ltm) 
@W: MO111 :"":0:0:0:-1|tristate driver N_35_t on net N_35 has its enable tied to GND (module v1392ltm) 
@W: MO111 :"":0:0:0:-1|tristate driver N_34_t on net N_34 has its enable tied to GND (module v1392ltm) 
@W: MO111 :"":0:0:0:-1|tristate driver N_33_t on net N_33 has its enable tied to GND (module v1392ltm) 
@W: MO111 :"":0:0:0:-1|tristate driver N_32_t on net N_32 has its enable tied to GND (module v1392ltm) 
@W: MO111 :"":0:0:0:-1|tristate driver N_31_t on net N_31 has its enable tied to GND (module v1392ltm) 
@W: MO111 :"":0:0:0:-1|tristate driver N_30_t on net N_30 has its enable tied to GND (module v1392ltm) 
@W: MO111 :"":0:0:0:-1|tristate driver N_2_t on net N_2 has its enable tied to GND (module v1392ltm) 
@W: MO111 :"":0:0:0:-1|tristate driver N_29_t on net N_29 has its enable tied to GND (module v1392ltm) 
@W: MO111 :"":0:0:0:-1|tristate driver N_28_t on net N_28 has its enable tied to GND (module v1392ltm) 
@W: MO111 :"":0:0:0:-1|tristate driver N_27_t on net N_27 has its enable tied to GND (module v1392ltm) 
@W: MO111 :"":0:0:0:-1|tristate driver N_26_t on net N_26 has its enable tied to GND (module v1392ltm) 
@W: MO111 :"":0:0:0:-1|tristate driver N_25_t on net N_25 has its enable tied to GND (module v1392ltm) 
@W: MO111 :"":0:0:0:-1|tristate driver N_24_t on net N_24 has its enable tied to GND (module v1392ltm) 
@W: MO111 :"":0:0:0:-1|tristate driver N_23_t on net N_23 has its enable tied to GND (module v1392ltm) 
@W: MO111 :"":0:0:0:-1|tristate driver N_22_t on net N_22 has its enable tied to GND (module v1392ltm) 
@W: MO111 :"":0:0:0:-1|tristate driver N_21_t on net N_21 has its enable tied to GND (module v1392ltm) 
@W: MO111 :"":0:0:0:-1|tristate driver N_20_t on net N_20 has its enable tied to GND (module v1392ltm) 
@W: MO111 :"":0:0:0:-1|tristate driver N_1_t on net N_1 has its enable tied to GND (module v1392ltm) 
@W: MO111 :"":0:0:0:-1|tristate driver N_19_t on net N_19 has its enable tied to GND (module v1392ltm) 
@W: MO111 :"":0:0:0:-1|tristate driver N_18_t on net N_18 has its enable tied to GND (module v1392ltm) 
@W: MO111 :"":0:0:0:-1|tristate driver N_17_t on net N_17 has its enable tied to GND (module v1392ltm) 
@W: MO111 :"":0:0:0:-1|tristate driver N_16_t on net N_16 has its enable tied to GND (module v1392ltm) 
@W: MO111 :"":0:0:0:-1|tristate driver N_15_t on net N_15 has its enable tied to GND (module v1392ltm) 
@W: MO111 :"":0:0:0:-1|tristate driver N_14_t on net N_14 has its enable tied to GND (module v1392ltm) 
@W: MO111 :"":0:0:0:-1|tristate driver N_13_t on net N_13 has its enable tied to GND (module v1392ltm) 
@W: MO111 :"":0:0:0:-1|tristate driver N_12_t on net N_12 has its enable tied to GND (module v1392ltm) 
@W: MO111 :"":0:0:0:-1|tristate driver N_11_t on net N_11 has its enable tied to GND (module v1392ltm) 
@W: MO111 :"":0:0:0:-1|tristate driver N_10_t on net N_10 has its enable tied to GND (module v1392ltm) 
@W: MO111 :"":0:0:0:-1|tristate driver SP_6 on net SP_6 has its enable tied to GND (module ctrl) 
@W: MO111 :"":0:0:0:-1|tristate driver SP_5 on net SP_5 has its enable tied to GND (module ctrl) 
@W: MO111 :"":0:0:0:-1|tristate driver SP_4 on net SP_4 has its enable tied to GND (module ctrl) 
@W: MO111 :"":0:0:0:-1|tristate driver SP_3 on net SP_3 has its enable tied to GND (module ctrl) 
@W: MO111 :"":0:0:0:-1|tristate driver SP_2 on net SP_2 has its enable tied to GND (module ctrl) 
@W: MO111 :"":0:0:0:-1|tristate driver SP_1 on net SP_1 has its enable tied to GND (module ctrl) 
@W: MO111 :"":0:0:0:-1|tristate driver undriven_inst on net undriven_net has its enable tied to GND (module VINTERF) 
@W: MO111 :"":0:0:0:-1|tristate driver undriven_inst on net undriven_net has its enable tied to GND (module RESET_MOD) 
@TM:1239285604
@N: MT195 :"":0:0:0:-1|This timing report estimates place and route data. Please look at the place and route timing report for final timing..
@TM:1239285513
@N: CD630 :"c:\frontend\annalisa\work\vx1392\hdl\clk_interf.vhd":22:7:22:16|M
@W: CL159 :"c:\frontend\annalisa\work\vx1392\hdl\clk_interf.vhd":24:7:24:9|M
@W: CL159 :"c:\frontend\annalisa\work\vx1392\hdl\clk_interf.vhd":25:7:25:11|M
@W: CL159 :"c:\frontend\annalisa\work\vx1392\hdl\clk_interf.vhd":45:7:45:11|M
@W: CL159 :"c:\frontend\annalisa\work\vx1392\hdl\clk_interf.vhd":46:7:46:10|M
@W: CL158 :"c:\frontend\annalisa\work\vx1392\hdl\clk_interf.vhd":48:7:48:11|M
@N: CD630 :"c:\frontend\annalisa\work\vx1392\hdl\ctrl.vhd":22:7:22:10|M
@W: CL159 :"c:\frontend\annalisa\work\vx1392\hdl\ctrl.vhd":37:6:37:10|M
@W: CL158 :"c:\frontend\annalisa\work\vx1392\hdl\ctrl.vhd":38:6:38:10|M
@W: CL209 :"c:\frontend\annalisa\work\vx1392\hdl\ctrl.vhd":39:6:39:9|M
@N: CD630 :"c:\frontend\annalisa\work\vx1392\hdl\dac_interf.vhd":24:7:24:16|M
@W: CL209 :"c:\frontend\annalisa\work\vx1392\hdl\dac_interf.vhd":46:7:46:11|M
@W: CL209 :"c:\frontend\annalisa\work\vx1392\hdl\dac_interf.vhd":47:7:47:10|M
@W: CL158 :"c:\frontend\annalisa\work\vx1392\hdl\dac_interf.vhd":49:7:49:11|M
@N: CD231 :"c:\frontend\annalisa\work\vx1392\hdl\dac_interf.vhd":59:17:59:18|M
@W:  :"c:\frontend\annalisa\work\vx1392\hdl\dac_interf.vhd":64:2:64:10|M
@W: CG296 :"c:\frontend\annalisa\work\vx1392\hdl\dac_interf.vhd":96:2:96:8|M
@N: CL201 :"c:\frontend\annalisa\work\vx1392\hdl\dac_interf.vhd":99:4:99:5|M
@W: CG290 :"c:\frontend\annalisa\work\vx1392\hdl\dac_interf.vhd":113:18:113:20|M
@W: CD604 :"c:\frontend\annalisa\work\vx1392\hdl\dac_interf.vhd":192:8:192:24|M
@N: CD630 :"c:\frontend\annalisa\work\vx1392\hdl\i2c_interf.vhd":27:7:27:16|M
@W: CL234 :"c:\frontend\annalisa\work\vx1392\hdl\i2c_interf.vhd":48:7:48:9|M
@W: CL209 :"c:\frontend\annalisa\work\vx1392\hdl\i2c_interf.vhd":49:7:49:11|M
@W: CL234 :"c:\frontend\annalisa\work\vx1392\hdl\i2c_interf.vhd":49:7:49:11|M
@W: CL234 :"c:\frontend\annalisa\work\vx1392\hdl\i2c_interf.vhd":50:7:50:10|M
@W: CL158 :"c:\frontend\annalisa\work\vx1392\hdl\i2c_interf.vhd":51:7:51:11|M
@N: CD231 :"c:\frontend\annalisa\work\vx1392\hdl\i2c_interf.vhd":61:17:61:18|M
@W:  :"c:\frontend\annalisa\work\vx1392\hdl\i2c_interf.vhd":66:2:66:10|M
@N: CD231 :"c:\frontend\annalisa\work\vx1392\hdl\i2c_interf.vhd":68:17:68:18|M
@W: CD639 :"c:\frontend\annalisa\work\vx1392\hdl\i2c_interf.vhd":97:10:97:13|M
@W: CL111 :"c:\frontend\annalisa\work\vx1392\hdl\i2c_interf.vhd":169:2:169:3|M
@N: CL201 :"c:\frontend\annalisa\work\vx1392\hdl\i2c_interf.vhd":169:2:169:3|M
@W: CL208 :"c:\frontend\annalisa\work\vx1392\hdl\i2c_interf.vhd":169:2:169:3|M
@W: CL170 :"c:\frontend\annalisa\work\vx1392\hdl\i2c_interf.vhd":306:4:306:5|M
@W: CL170 :"c:\frontend\annalisa\work\vx1392\hdl\i2c_interf.vhd":329:3:329:4|M
@N: CL201 :"c:\frontend\annalisa\work\vx1392\hdl\i2c_interf.vhd":329:3:329:4|M
@W: CD604 :"c:\frontend\annalisa\work\vx1392\hdl\i2c_interf.vhd":436:12:436:32|M
@N: CD630 :"c:\frontend\annalisa\work\vx1392\hdl\lbspare.vhd":23:7:23:13|M
@N: CD630 :"c:\frontend\annalisa\work\vx1392\hdl\monostable.vhd":24:7:24:16|M
@W: BN116 :"c:\frontend\annalisa\work\vx1392\hdl\monostable.vhd":57:4:57:5|M
@W: BN132 :"c:\frontend\annalisa\work\vx1392\hdl\monostable.vhd":57:4:57:5|M
@N: CD630 :"c:\frontend\annalisa\work\vx1392\hdl\pdl_interf.vhd":27:7:27:16|M
@W: CL159 :"c:\frontend\annalisa\work\vx1392\hdl\pdl_interf.vhd":31:10:31:14|M
@W: CL158 :"c:\frontend\annalisa\work\vx1392\hdl\pdl_interf.vhd":54:10:54:14|M
@W: CL234 :"c:\frontend\annalisa\work\vx1392\hdl\pdl_interf.vhd":56:10:56:12|M
@W: CL209 :"c:\frontend\annalisa\work\vx1392\hdl\pdl_interf.vhd":57:10:57:14|M
@W: CL234 :"c:\frontend\annalisa\work\vx1392\hdl\pdl_interf.vhd":57:10:57:14|M
@W: CL159 :"c:\frontend\annalisa\work\vx1392\hdl\pdl_interf.vhd":58:10:58:13|M
@N: CD231 :"c:\frontend\annalisa\work\vx1392\hdl\pdl_interf.vhd":66:17:66:18|M
@W:  :"c:\frontend\annalisa\work\vx1392\hdl\pdl_interf.vhd":71:2:71:10|M
@W: CG296 :"c:\frontend\annalisa\work\vx1392\hdl\pdl_interf.vhd":112:2:112:8|M
@N: CL201 :"c:\frontend\annalisa\work\vx1392\hdl\pdl_interf.vhd":115:4:115:5|M
@W: CG290 :"c:\frontend\annalisa\work\vx1392\hdl\pdl_interf.vhd":127:19:127:21|M
@TM:1239286877
@W: CD604 :"c:\frontend\annalisa\work\vx1392\hdl\pdl_interf.vhd":278:9:278:25|M
@TM:1239285513
@N: CD630 :"c:\frontend\annalisa\work\vx1392\hdl\reset_mod.vhd":31:7:31:15|M
@W: CL234 :"c:\frontend\annalisa\work\vx1392\hdl\reset_mod.vhd":56:7:56:11|M
@W: CL209 :"c:\frontend\annalisa\work\vx1392\hdl\reset_mod.vhd":58:7:58:11|M
@W: CL234 :"c:\frontend\annalisa\work\vx1392\hdl\reset_mod.vhd":58:7:58:11|M
@W: CL234 :"c:\frontend\annalisa\work\vx1392\hdl\reset_mod.vhd":59:7:59:9|M
@N: MF238 :"c:\frontend\annalisa\work\vx1392\hdl\reset_mod.vhd":111:18:111:29|M
@TM:1240400151
@N: MF238 :"c:\frontend\annalisa\work\vx1392\hdl\reset_mod.vhd":177:18:177:25|M
@N: MF238 :"c:\frontend\annalisa\work\vx1392\hdl\reset_mod.vhd":180:20:180:27|M
@N: MF238 :"c:\frontend\annalisa\work\vx1392\hdl\reset_mod.vhd":241:15:241:23|M
@TM:1239285513
@N: CD630 :"c:\frontend\annalisa\work\vx1392\hdl\roc32.vhd":28:7:28:11|M
@W: CL159 :"c:\frontend\annalisa\work\vx1392\hdl\roc32.vhd":81:7:81:13|M
@W: CL159 :"c:\frontend\annalisa\work\vx1392\hdl\roc32.vhd":82:7:82:13|M
@W: CL159 :"c:\frontend\annalisa\work\vx1392\hdl\roc32.vhd":83:7:83:13|M
@W: CL163 :"c:\frontend\annalisa\work\vx1392\hdl\roc32.vhd":91:7:91:11|M
@W: CL158 :"c:\frontend\annalisa\work\vx1392\hdl\roc32.vhd":103:7:103:11|M
@W: CL209 :"c:\frontend\annalisa\work\vx1392\hdl\roc32.vhd":106:7:106:9|M
@W: CL234 :"c:\frontend\annalisa\work\vx1392\hdl\roc32.vhd":106:7:106:9|M
@W: CL159 :"c:\frontend\annalisa\work\vx1392\hdl\roc32.vhd":107:7:107:10|M
@W: CL209 :"c:\frontend\annalisa\work\vx1392\hdl\roc32.vhd":108:7:108:11|M
@W: CL234 :"c:\frontend\annalisa\work\vx1392\hdl\roc32.vhd":108:7:108:11|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\hdl\roc32.vhd":144:9:144:18|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\hdl\roc32.vhd":145:9:145:18|M
@W: CD279 :"c:\frontend\annalisa\work\vx1392\hdl\roc32.vhd":291:6:291:7|M
@W: CD279 :"c:\frontend\annalisa\work\vx1392\hdl\roc32.vhd":292:6:292:7|M
@W: CD279 :"c:\frontend\annalisa\work\vx1392\hdl\roc32.vhd":300:6:300:8|M
@W: CD279 :"c:\frontend\annalisa\work\vx1392\hdl\roc32.vhd":301:6:301:8|M
@W:  :"c:\frontend\annalisa\work\vx1392\hdl\roc32.vhd":326:2:326:5|M
@N: CD231 :"c:\frontend\annalisa\work\vx1392\hdl\roc32.vhd":326:15:326:16|M
@N: CD233 :"c:\frontend\annalisa\work\vx1392\hdl\roc32.vhd":333:15:333:16|M
@N: MF238 :"c:\frontend\annalisa\work\vx1392\hdl\roc32.vhd":566:24:566:34|M
@N: CL201 :"c:\frontend\annalisa\work\vx1392\hdl\roc32.vhd":583:4:583:5|M
@N: CL201 :"c:\frontend\annalisa\work\vx1392\hdl\roc32.vhd":638:4:638:5|M
@TM:1239286025
@N: MO106 :"c:\frontend\annalisa\work\vx1392\hdl\roc32.vhd":753:42:753:48|M
@W: CD604 :"c:\frontend\annalisa\work\vx1392\hdl\roc32.vhd":888:8:888:26|M
@TM:1240400151
@N: CD630 :"c:\frontend\annalisa\work\vx1392\hdl\spi_interf.vhd":41:7:41:16|M
@W: CL159 :"c:\frontend\annalisa\work\vx1392\hdl\spi_interf.vhd":49:7:49:13|M
@W: CL234 :"c:\frontend\annalisa\work\vx1392\hdl\spi_interf.vhd":84:7:84:9|M
@W: CL234 :"c:\frontend\annalisa\work\vx1392\hdl\spi_interf.vhd":85:7:85:11|M
@W: CL158 :"c:\frontend\annalisa\work\vx1392\hdl\spi_interf.vhd":86:7:86:11|M
@W: CL209 :"c:\frontend\annalisa\work\vx1392\hdl\spi_interf.vhd":87:7:87:10|M
@W: CL234 :"c:\frontend\annalisa\work\vx1392\hdl\spi_interf.vhd":87:7:87:10|M
@N: CD231 :"c:\frontend\annalisa\work\vx1392\hdl\spi_interf.vhd":99:17:99:18|M
@W:  :"c:\frontend\annalisa\work\vx1392\hdl\spi_interf.vhd":111:2:111:10|M
@W: CL171 :"c:\frontend\annalisa\work\vx1392\hdl\spi_interf.vhd":265:4:265:5|M
@W: CL190 :"c:\frontend\annalisa\work\vx1392\hdl\spi_interf.vhd":265:4:265:5|M
@N: CL201 :"c:\frontend\annalisa\work\vx1392\hdl\spi_interf.vhd":265:4:265:5|M
@TM:1240400997
@W: CD604 :"c:\frontend\annalisa\work\vx1392\hdl\spi_interf.vhd":557:8:557:24|M
@W: CL169 :"c:\frontend\annalisa\work\vx1392\hdl\spi_interf.vhd":588:4:588:5|M
@W: CL171 :"c:\frontend\annalisa\work\vx1392\hdl\spi_interf.vhd":588:4:588:5|M
@N: CL177 :"c:\frontend\annalisa\work\vx1392\hdl\spi_interf.vhd":588:4:588:5|M
@W: CL189 :"c:\frontend\annalisa\work\vx1392\hdl\spi_interf.vhd":588:4:588:5|M
@TM:1239285513
@N: CD630 :"c:\frontend\annalisa\work\vx1392\hdl\v1392ltm.vhd":21:7:21:14|M
@W: MO111 :"c:\frontend\annalisa\work\vx1392\hdl\v1392ltm.vhd":150:10:150:14|M
@TM:1240415196
@N: CD630 :"c:\frontend\annalisa\work\vx1392\hdl\vinterf.vhd":52:7:52:13|M
@W: CL159 :"c:\frontend\annalisa\work\vx1392\hdl\vinterf.vhd":67:7:67:13|M
@W: CL159 :"c:\frontend\annalisa\work\vx1392\hdl\vinterf.vhd":71:7:71:13|M
@W: CL159 :"c:\frontend\annalisa\work\vx1392\hdl\vinterf.vhd":92:7:92:11|M
@W: CL159 :"c:\frontend\annalisa\work\vx1392\hdl\vinterf.vhd":94:7:94:9|M
@W: CL159 :"c:\frontend\annalisa\work\vx1392\hdl\vinterf.vhd":95:7:95:9|M
@W: CL159 :"c:\frontend\annalisa\work\vx1392\hdl\vinterf.vhd":97:7:97:17|M
@W: CL159 :"c:\frontend\annalisa\work\vx1392\hdl\vinterf.vhd":123:7:123:13|M
@W: CL159 :"c:\frontend\annalisa\work\vx1392\hdl\vinterf.vhd":124:7:124:13|M
@W: CL209 :"c:\frontend\annalisa\work\vx1392\hdl\vinterf.vhd":137:7:137:11|M
@W: CL209 :"c:\frontend\annalisa\work\vx1392\hdl\vinterf.vhd":142:7:142:9|M
@W: CL234 :"c:\frontend\annalisa\work\vx1392\hdl\vinterf.vhd":142:7:142:9|M
@W: CL209 :"c:\frontend\annalisa\work\vx1392\hdl\vinterf.vhd":144:7:144:10|M
@W: CD639 :"c:\frontend\annalisa\work\vx1392\hdl\vinterf.vhd":247:9:247:12|M
@W: CD639 :"c:\frontend\annalisa\work\vx1392\hdl\vinterf.vhd":248:9:248:12|M
@W: CD639 :"c:\frontend\annalisa\work\vx1392\hdl\vinterf.vhd":249:9:249:12|M
@W:  :"c:\frontend\annalisa\work\vx1392\hdl\vinterf.vhd":265:2:265:5|M
@W:  :"c:\frontend\annalisa\work\vx1392\hdl\vinterf.vhd":265:2:265:5|M
@W:  :"c:\frontend\annalisa\work\vx1392\hdl\vinterf.vhd":265:2:265:5|M
@N: CD231 :"c:\frontend\annalisa\work\vx1392\hdl\vinterf.vhd":265:17:265:18|M
@W: CD136 :"c:\frontend\annalisa\work\vx1392\hdl\vinterf.vhd":269:46:269:53|M
@W: CD136 :"c:\frontend\annalisa\work\vx1392\hdl\vinterf.vhd":269:46:269:53|M
@W: CD136 :"c:\frontend\annalisa\work\vx1392\hdl\vinterf.vhd":269:46:269:53|M
@N: CD231 :"c:\frontend\annalisa\work\vx1392\hdl\vinterf.vhd":272:17:272:18|M
@N: CD231 :"c:\frontend\annalisa\work\vx1392\hdl\vinterf.vhd":279:17:279:18|M
@W: CL117 :"c:\frontend\annalisa\work\vx1392\hdl\vinterf.vhd":449:4:449:5|M
@N: CL177 :"c:\frontend\annalisa\work\vx1392\hdl\vinterf.vhd":449:4:449:5|M
@W: CL171 :"c:\frontend\annalisa\work\vx1392\hdl\vinterf.vhd":470:4:470:5|M
@W: CL190 :"c:\frontend\annalisa\work\vx1392\hdl\vinterf.vhd":470:4:470:5|M
@W: CL169 :"c:\frontend\annalisa\work\vx1392\hdl\vinterf.vhd":517:4:517:5|M
@W: BN116 :"c:\frontend\annalisa\work\vx1392\hdl\vinterf.vhd":562:4:562:5|M
@W: BN132 :"c:\frontend\annalisa\work\vx1392\hdl\vinterf.vhd":562:4:562:5|M
@W: CL169 :"c:\frontend\annalisa\work\vx1392\hdl\vinterf.vhd":562:4:562:5|M
@W: CL171 :"c:\frontend\annalisa\work\vx1392\hdl\vinterf.vhd":562:4:562:5|M
@W: CL171 :"c:\frontend\annalisa\work\vx1392\hdl\vinterf.vhd":562:4:562:5|M
@W: CL190 :"c:\frontend\annalisa\work\vx1392\hdl\vinterf.vhd":562:4:562:5|M
@W: CL190 :"c:\frontend\annalisa\work\vx1392\hdl\vinterf.vhd":562:4:562:5|M
@N: CL201 :"c:\frontend\annalisa\work\vx1392\hdl\vinterf.vhd":562:4:562:5|M
@N: CL201 :"c:\frontend\annalisa\work\vx1392\hdl\vinterf.vhd":979:4:979:5|M
@W: CL169 :"c:\frontend\annalisa\work\vx1392\hdl\vinterf.vhd":1140:4:1140:5|M
@W: CL190 :"c:\frontend\annalisa\work\vx1392\hdl\vinterf.vhd":1140:4:1140:5|M
@N: CL201 :"c:\frontend\annalisa\work\vx1392\hdl\vinterf.vhd":1140:4:1140:5|M
@TM:1239285513
@N: CD630 :"c:\frontend\annalisa\work\vx1392\smartgen\crom\crom.vhd":4:7:4:10|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\crom\crom.vhd":99:7:99:14|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\crom\crom.vhd":99:57:99:64|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\crom\crom.vhd":99:67:99:74|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\crom\crom.vhd":99:77:99:84|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\crom\crom.vhd":100:6:100:13|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\crom\crom.vhd":100:66:100:73|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\crom\crom.vhd":100:76:100:83|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\crom\crom.vhd":101:36:101:43|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\crom\crom.vhd":101:46:101:53|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\crom\crom.vhd":102:6:102:13|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\crom\crom.vhd":102:16:102:23|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\crom\crom.vhd":102:56:102:63|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\crom\crom.vhd":102:66:102:73|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\crom\crom.vhd":103:26:103:33|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\crom\crom.vhd":103:36:103:43|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\crom\crom.vhd":103:76:103:83|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\crom\crom.vhd":104:6:104:13|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\crom\crom.vhd":104:46:104:53|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\crom\crom.vhd":104:56:104:63|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\crom\crom.vhd":105:16:105:23|M
@N: CD630 :"c:\frontend\annalisa\work\vx1392\smartgen\daccfg\daccfg.vhd":4:7:4:12|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\daccfg\daccfg.vhd":74:7:74:14|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\daccfg\daccfg.vhd":74:27:74:34|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\daccfg\daccfg.vhd":74:37:74:44|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\daccfg\daccfg.vhd":74:47:74:54|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\daccfg\daccfg.vhd":74:57:74:64|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\daccfg\daccfg.vhd":74:67:74:74|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\daccfg\daccfg.vhd":74:77:74:84|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\daccfg\daccfg.vhd":75:6:75:13|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\daccfg\daccfg.vhd":75:16:75:23|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\daccfg\daccfg.vhd":75:26:75:33|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\daccfg\daccfg.vhd":75:36:75:43|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\daccfg\daccfg.vhd":75:46:75:53|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\daccfg\daccfg.vhd":75:56:75:63|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\daccfg\daccfg.vhd":75:66:75:73|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\daccfg\daccfg.vhd":75:76:75:83|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\daccfg\daccfg.vhd":76:6:76:13|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\daccfg\daccfg.vhd":76:16:76:23|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\daccfg\daccfg.vhd":76:26:76:33|M
@N: CD630 :"c:\frontend\annalisa\work\vx1392\smartgen\event_fifo\event_fifo.vhd":4:7:4:16|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\event_fifo\event_fifo.vhd":95:27:95:34|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\event_fifo\event_fifo.vhd":97:76:97:83|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\event_fifo\event_fifo.vhd":98:6:98:13|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\event_fifo\event_fifo.vhd":98:16:98:23|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\event_fifo\event_fifo.vhd":98:26:98:33|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\event_fifo\event_fifo.vhd":98:36:98:43|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\event_fifo\event_fifo.vhd":98:46:98:53|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\event_fifo\event_fifo.vhd":98:56:98:63|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\event_fifo\event_fifo.vhd":98:66:98:73|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\event_fifo\event_fifo.vhd":98:76:98:83|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\event_fifo\event_fifo.vhd":99:6:99:13|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\event_fifo\event_fifo.vhd":99:16:99:23|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\event_fifo\event_fifo.vhd":99:26:99:33|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\event_fifo\event_fifo.vhd":99:36:99:43|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\event_fifo\event_fifo.vhd":99:46:99:53|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\event_fifo\event_fifo.vhd":99:56:99:63|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\event_fifo\event_fifo.vhd":99:66:99:73|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\event_fifo\event_fifo.vhd":99:76:99:83|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\event_fifo\event_fifo.vhd":100:6:100:13|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\event_fifo\event_fifo.vhd":100:16:100:23|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\event_fifo\event_fifo.vhd":100:26:100:33|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\event_fifo\event_fifo.vhd":100:36:100:43|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\event_fifo\event_fifo.vhd":100:46:100:53|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\event_fifo\event_fifo.vhd":100:56:100:63|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\event_fifo\event_fifo.vhd":100:66:100:73|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\event_fifo\event_fifo.vhd":100:76:100:83|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\event_fifo\event_fifo.vhd":101:6:101:13|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\event_fifo\event_fifo.vhd":101:16:101:23|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\event_fifo\event_fifo.vhd":101:26:101:33|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\event_fifo\event_fifo.vhd":101:36:101:43|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\event_fifo\event_fifo.vhd":101:46:101:53|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\event_fifo\event_fifo.vhd":101:56:101:63|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\event_fifo\event_fifo.vhd":101:66:101:73|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\event_fifo\event_fifo.vhd":101:76:101:83|M
@N: CD630 :"c:\frontend\annalisa\work\vx1392\smartgen\pdlcfg\pdlcfg.vhd":4:7:4:12|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\pdlcfg\pdlcfg.vhd":74:7:74:14|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\pdlcfg\pdlcfg.vhd":74:27:74:34|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\pdlcfg\pdlcfg.vhd":74:37:74:44|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\pdlcfg\pdlcfg.vhd":74:47:74:54|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\pdlcfg\pdlcfg.vhd":74:57:74:64|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\pdlcfg\pdlcfg.vhd":74:67:74:74|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\pdlcfg\pdlcfg.vhd":74:77:74:84|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\pdlcfg\pdlcfg.vhd":75:6:75:13|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\pdlcfg\pdlcfg.vhd":75:16:75:23|M
@W: CD638 :"c:\frontend\annalisa\work\vx1392\smartgen\pdlcfg\pdlcfg.vhd":75:26:75:33|M
@N: CD630 :"c:\programmi\libero73\synplify\synplify_862h\lib\proasic\proasicplus.vhd":59:10:59:12|M
@N: CD630 :"c:\programmi\libero73\synplify\synplify_862h\lib\proasic\proasicplus.vhd":145:10:145:12|M
@N: CD630 :"c:\programmi\libero73\synplify\synplify_862h\lib\proasic\proasicplus.vhd":297:10:297:12|M
@N: CD630 :"c:\programmi\libero73\synplify\synplify_862h\lib\proasic\proasicplus.vhd":321:10:321:14|M
@N: CD630 :"c:\programmi\libero73\synplify\synplify_862h\lib\proasic\proasicplus.vhd":493:10:493:12|M
@N: CD630 :"c:\programmi\libero73\synplify\synplify_862h\lib\proasic\proasicplus.vhd":3846:10:3846:13|M
@N: CD630 :"c:\programmi\libero73\synplify\synplify_862h\lib\proasic\proasicplus.vhd":4467:10:4467:21|M
@N: CD630 :"c:\programmi\libero73\synplify\synplify_862h\lib\proasic\proasicplus.vhd":4706:10:4706:21|M
@N: CD630 :"c:\programmi\libero73\synplify\synplify_862h\lib\proasic\proasicplus.vhd":5079:7:5079:9|M
@N: CD630 :"c:\programmi\libero73\synplify\synplify_862h\lib\proasic\proasicplus.vhd":5092:7:5092:9|M
@TM:1239285301
@N: CD720 :"c:\programmi\libero73\synplify\synplify_862h\lib\vhd\std.vhd":123:18:123:21|M
