-- VHDL Entity vx1392_lib.vbuf.symbol
--
-- Created:
--          by - daprato.UNKNOWN (LUCA-FE)
--          at - 12:07:36 21/11/2005
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2003.2 (Build 28)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY vbuf IS
   PORT( 
      ADLTC    : IN     std_logic;
      AM       : IN     std_logic_vector (5 DOWNTO 0);
      AS       : IN     std_logic;
      DS0      : IN     std_logic;
      DS1      : IN     std_logic;
      IACK     : IN     std_logic;
      IACKIN   : IN     std_logic;
      IACKOUTB : IN     std_logic;
      INTR1    : IN     std_logic;
      INTR2    : IN     std_logic;
      MYBERR   : IN     std_logic;
      NDTKIN   : IN     std_logic;
      NOE16R   : IN     std_logic;
      NOE16W   : IN     std_logic;
      NOE32R   : IN     std_logic;
      NOE32W   : IN     std_logic;
      NOE64R   : IN     std_logic;
      NOEAD    : IN     std_logic;
      NOEDTK   : IN     std_logic;
      SPSEI    : IN     std_logic;
      SPSEOB   : IN     std_logic;
      SPULSE0  : IN     std_logic;
      SPULSE1  : IN     std_logic;
      SPULSE2  : IN     std_logic;
      SYSRES   : IN     std_logic;
      WRITE    : IN     std_logic;
      AMB      : OUT    std_logic_vector (5 DOWNTO 0);
      ASB      : OUT    std_logic;
      BERR     : OUT    std_logic;
      BERRVME  : OUT    std_logic;
      DS0B     : OUT    std_logic;
      DS1B     : OUT    std_logic;
      DTACK    : OUT    std_logic;
      IACKB    : OUT    std_logic;
      IACKINB  : OUT    std_logic;
      IACKOUT  : OUT    std_logic;
      IRQ1     : OUT    std_logic;
      IRQ2     : OUT    std_logic;
      SPSEIB   : OUT    std_logic;
      SPSEO    : OUT    std_logic;
      SPULSE0B : OUT    std_logic;
      SPULSE1B : OUT    std_logic;
      SPULSE2B : OUT    std_logic;
      SYSRESB  : OUT    std_logic;
      WRITEB   : OUT    std_logic;
      A        : INOUT  std_logic_vector (31 DOWNTO 1);
      D        : INOUT  std_logic_vector (31 DOWNTO 0);
      LWORD    : INOUT  std_logic;
      LWORDB   : INOUT  std_logic;
      VAD      : INOUT  std_logic_vector (31 DOWNTO 1);
      VDB      : INOUT  std_logic_vector (31 DOWNTO 0)
   );

-- Declarations

END vbuf ;

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF vbuf IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL B    : std_logic_vector(6 DOWNTO 0);
   SIGNAL GND  : std_logic;
   SIGNAL VDD  : std_logic;
   SIGNAL Y22  : std_logic;
   SIGNAL Y23  : std_logic;
   SIGNAL Y24  : std_logic;
   SIGNAL dout : std_logic_vector(6 DOWNTO 0);

   -- Implicit buffer signal declarations
   SIGNAL BERR_internal : std_logic;


   -- ModuleWare signal declarations(v1.1) for instance 'I22' of 'split'
   SIGNAL mw_I22din : std_logic_vector(6 DOWNTO 0);

   -- Component Declarations
   COMPONENT FCT16543P
   GENERIC (
      SIZE : integer
   );
   PORT (
      NCEAB : IN     std_logic ;
      NCEBA : IN     std_logic ;
      NLEAB : IN     std_logic ;
      NLEBA : IN     std_logic ;
      NOEAB : IN     std_logic ;
      NOEBA : IN     std_logic ;
      A     : INOUT  std_logic_vector ;
      B     : INOUT  std_logic_vector 
   );
   END COMPONENT;
   COMPONENT FCT1BIT543
   PORT (
      NCEAB : IN     std_logic ;
      NCEBA : IN     std_logic ;
      NLEAB : IN     std_logic ;
      NLEBA : IN     std_logic ;
      NOEAB : IN     std_logic ;
      NOEBA : IN     std_logic ;
      A     : INOUT  std_logic ;
      B     : INOUT  std_logic 
   );
   END COMPONENT;
   COMPONENT LVC16244
   PORT (
      A1  : IN     std_logic ;
      A2  : IN     std_logic ;
      A3  : IN     std_logic ;
      A4  : IN     std_logic ;
      NOE : IN     std_logic ;
      Y1  : OUT    std_logic ;
      Y2  : OUT    std_logic ;
      Y3  : OUT    std_logic ;
      Y4  : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT LVT125
   PORT (
      A1   : IN     std_logic ;
      A2   : IN     std_logic ;
      A3   : IN     std_logic ;
      A4   : IN     std_logic ;
      NOE1 : IN     std_logic ;
      NOE2 : IN     std_logic ;
      NOE3 : IN     std_logic ;
      NOE4 : IN     std_logic ;
      Y1   : OUT    std_logic ;
      Y2   : OUT    std_logic ;
      Y3   : OUT    std_logic ;
      Y4   : OUT    std_logic 
   );
   END COMPONENT;


BEGIN

   -- ModuleWare code(v1.1) for instance 'I1' of 'gnd'
   GND <= '0';

   -- ModuleWare code(v1.1) for instance 'I25' of 'merge'
   dout <= IACK & AM(5) & AM(4) & AM(3) & AM(2) & AM(1) & AM(0);

   -- ModuleWare code(v1.1) for instance 'I22' of 'split'
   mw_I22din <= B;
   I22combo: PROCESS (mw_I22din)
   VARIABLE itemp: std_logic_vector(6 DOWNTO 0);
   BEGIN
      itemp := mw_I22din(6 DOWNTO 0);
      AMB(0) <= itemp(0);
      AMB(1) <= itemp(1);
      AMB(2) <= itemp(2);
      AMB(3) <= itemp(3);
      AMB(4) <= itemp(4);
      AMB(5) <= itemp(5);
      IACKB <= itemp(6);
   END PROCESS I22combo;

   -- ModuleWare code(v1.1) for instance 'I2' of 'vdd'
   VDD <= '1';

   -- Instance port mappings.
   I0 : FCT16543P
      GENERIC MAP (
         SIZE => 16
      )
      PORT MAP (
         NCEAB => GND,
         NCEBA => GND,
         NLEAB => GND,
         NLEBA => GND,
         NOEAB => NOE16W,
         NOEBA => NOE16R,
         A     => D(15 DOWNTO 0),
         B     => VDB(15 DOWNTO 0)
      );
   I3 : FCT16543P
      GENERIC MAP (
         SIZE => 16
      )
      PORT MAP (
         NCEAB => GND,
         NCEBA => GND,
         NLEAB => GND,
         NLEBA => GND,
         NOEAB => NOE32W,
         NOEBA => NOE32R,
         A     => D(31 DOWNTO 16),
         B     => VDB(31 DOWNTO 16)
      );
   I4 : FCT16543P
      GENERIC MAP (
         SIZE => 31
      )
      PORT MAP (
         NCEAB => GND,
         NCEBA => GND,
         NLEAB => ADLTC,
         NLEBA => GND,
         NOEAB => NOEAD,
         NOEBA => NOE64R,
         A     => A,
         B     => VAD
      );
   I6 : FCT16543P
      GENERIC MAP (
         SIZE => 7
      )
      PORT MAP (
         NCEAB => GND,
         NCEBA => VDD,
         NLEAB => ADLTC,
         NLEBA => VDD,
         NOEAB => GND,
         NOEBA => VDD,
         A     => dout,
         B     => B
      );
   I5 : FCT1BIT543
      GENERIC MAP (
         SIZE => 1
      )
      PORT MAP (
         NCEAB => GND,
         NCEBA => GND,
         NLEAB => ADLTC,
         NLEBA => GND,
         NOEAB => NOEAD,
         NOEBA => NOE64R,
         A     => LWORD,
         B     => LWORDB
      );
   I7 : LVC16244
      PORT MAP (
         A1  => IACKIN,
         A2  => AS,
         A3  => WRITE,
         A4  => IACKOUTB,
         NOE => GND,
         Y1  => IACKINB,
         Y2  => ASB,
         Y3  => WRITEB,
         Y4  => IACKOUT
      );
   I8 : LVC16244
      PORT MAP (
         A1  => DS0,
         A2  => DS1,
         A3  => BERR_internal,
         A4  => SYSRES,
         NOE => GND,
         Y1  => DS0B,
         Y2  => DS1B,
         Y3  => BERRVME,
         Y4  => SYSRESB
      );
   I11 : LVC16244
      PORT MAP (
         A1  => SPSEI,
         A2  => SPULSE0,
         A3  => SPULSE1,
         A4  => SPULSE2,
         NOE => GND,
         Y1  => SPSEIB,
         Y2  => SPULSE0B,
         Y3  => SPULSE1B,
         Y4  => SPULSE2B
      );
   I12 : LVC16244
      PORT MAP (
         A1  => SPSEOB,
         A2  => GND,
         A3  => GND,
         A4  => GND,
         NOE => GND,
         Y1  => SPSEO,
         Y2  => Y22,
         Y3  => Y24,
         Y4  => Y23
      );
   I15 : LVT125
      PORT MAP (
         A1   => NDTKIN,
         A2   => GND,
         A3   => GND,
         A4   => GND,
         NOE1 => NOEDTK,
         NOE2 => MYBERR,
         NOE3 => INTR1,
         NOE4 => INTR2,
         Y1   => DTACK,
         Y2   => BERR_internal,
         Y3   => IRQ1,
         Y4   => IRQ2
      );

   -- Implicit buffered output assignments
   BERR <= BERR_internal;

END struct;
